blog_resep/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('', include('reseppage.urls')),
]

main/urls.py
from django.urls import path

from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
]

reseppage/urls.py
from django.urls import path

from . import views

app_name = 'reseppage'

urlpatterns = [
    path('tambahkategoriresep/', views.kategori, name='kategori'),
    path('resep/<int:resep_id>', views.resep, name='resep'),
    path('lihatresep/', views.lihat, name='lihat'),
]

main/models.py
from django.db import models

# Create your models here.

reseppage/models.py
from django.db import models

# Create your models here.
class listKategori(models.Model):
    namaKategori = models.CharField(max_length=300)

class listResep(models.Model):
    namaResep = models.CharField(max_length=30)
    url = models.CharField(max_length= 100, default = True)
    kategori = models.ForeignKey(listKategori, on_delete=models.CASCADE, default = True)

reseppage/forms.py
from django import forms
from .models import listKategori,listResep

class formKategori(forms.Form):
    class Meta:
        model = listKategori
        fields = "__all__"

    input_attrs = {
        'type' : 'text',
        'placeholder' : 'Maks 30 karakter'
    }
    
    namaKategori = forms.CharField(label = 'Nama Kategori Resep', required=True,
        max_length=30, widget=forms.TextInput(attrs=input_attrs))

class formResep(forms.Form):
    class Meta:
        model = listResep
        fields = "__all__"
    
    input_attrs = {
        'type' : 'text',
        'placeholder' : 'Maks 30 karakter'
    }

    input_attrs1 = {
        'type' : 'text',
        'placeholder' : 'Masukkan URL resep'
    }

    namaResep = forms.CharField(label = 'Nama Resep', required=True,
        max_length=30, widget=forms.TextInput(attrs=input_attrs))
    url = forms.CharField(label = 'URL', required=True,
        max_length=100, widget=forms.TextInput(attrs=input_attrs1))

main/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main/login.html')

reseppage/views.py
from django.shortcuts import render
from .forms import *
from .models import *

# Create your views here.
def kategori(request):
    kategori = listKategori.objects.all()
    kategoris= formKategori(request.POST or None)
    context = {
        'kategori' : kategori,
        'kategoris' : kategoris
    }
    if request.method == 'POST' :
        if kategoris.is_valid():
            kategori.create(
                namaKategori = kategoris.cleaned_data.get('namaKategori')
            )
    return render(request, 'kategori.html', context)

def resep(request, resep_id) :
    kategori= listKategori.objects.get(id=resep_id)
    resep = listResep.objects.all()
    form_resep = formResep(request.POST or None)
    context = {
        'kategori':kategori,
		'form_resep':form_resep,
		'resep':resep,
    }
    if request.method == 'POST' :
        if form_resep.is_valid():
            resep.create(
                namaResep=form_resep.cleaned_data.get('namaResep'),
                url = form_resep.cleaned_data.get('url'),
                kategori=kategori
            )
    return render(request, 'resep.html', context)

def lihat(request):
    return render(request, 'lihat.html')

main/templates/main/login.html
{% extends 'base.html' %}
{% load static %}

{% block title%}login{% endblock title %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'home.css' %}">
{% endblock additional_css %}

{% block content %}
  <h1>Hello, Mama!</h1>
{% endblock content %}

reseppage/templates/kategori.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Daftar Resep{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'reseps.css' %}">
{% endblock additional_css %}

{% block content %}
    <div class="jumbotron jumbotron-fluid" id = "gambar">
        <div class="container">
            <h1 class="display-4" id="judul">TAMBAH RESEP &#128071</h1>
            <p class="lead" id = "par">Tambah Resep Simpanan Mama Disini</p>
        </div>
    </div>
    <form method="POST">
        {% csrf_token %}
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{kategoris.namaKategori.label_tag}}
                </div>
                <div class="col-sm-10">
                    {{kategoris.namaKategori}}
                </div>
            </div>
            <input type = "submit" value = "Tambahkan" id = "submit">

        <br><br><br>
    
        <table class="table table-striped">
        <thead>
            <tr>
            <th scope="col">Nama Kategori</th>
            </tr>
        </thead>
        <tbody>
            {% for kat in kategori %}
            <tr>
                <th scope="row">{{kat.namaKategori}}</th>
                <td><a href="{% url 'reseppage:resep' resep_id=kat.id %}" class="btn">Lihat/Tambahkan Resep</a></td>
            </tr>
        </tbody>
        {% endfor %}
{% endblock content %}

reseppage/templates/lihat.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Daftar Resep{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'resep.css' %}">
{% endblock additional_css %}

{% block content %}
    <div class="jumbotron jumbotron-fluid" id = "gambar">
        <div class="container">
            <h1 class="display-4" id="judul">DAFTAR RESEP &#128071</h1>
            <p class="lead" id = "par">Cari Resep Simpanan Mama Disini</p>
        </div>
    </div>

    <form method="POST">
        {% csrf_token %}
        <table>
            {{form_resep.as_table}}
        </table>
        <button type="Submit" name="submit">Submit</button>
    
        <table class="table table-dark table-striped">
      <thead>
        <tr>
          <th scope="col">Nama Siswa</th>
        </tr>
        </thead>
        <tbody>
            {% for res in resep %}
            <tr>
                {% if res.kategori == kategori %}
                <th scope="row">{{res.namaResep}}</th>
                <th scope="row">{{res.url}}</th>
                {% endif %} 
            </tr>
        </tbody>
        {% endfor %}
{% endblock content %}

reseppage/templates/resep.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Daftar Resep{% endblock %}

{% block additional_css %}
    <link rel="stylesheet" href="{% static 'reseps.css' %}">
{% endblock additional_css %}

{% block content %}
    <div class="jumbotron jumbotron-fluid" id = "gambar">
        <div class="container">
            <h1 class="display-4" id="judul">TAMBAH RESEP &#128071</h1>
            <p class="lead" id = "par">Tambah Resep Simpanan Mama Disini</p>
        </div>
    </div>
    <form method = "POST">
        {% csrf_token %}
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{form_resep.namaResep.label_tag}}
                </div>
                <div class="col-sm-10">
                    {{form_resep.namaResep}}
                </div>
            </div>
            <div class="form-group row">
                <div class="col-sm-2 col-form-label">
                    {{form_resep.url.label_tag}}
                </div>
                <div class="col-sm-10">
                    {{form_resep.url}}
                </div>
            </div>
        <input type = "submit" value = "Tambahkan" id = "submit">

        <br><br><br>

        <table class="table table-striped">
            <thead>
              <tr>
                <th scope="col">Nama Resep</th>
                <th scope="col">Link</th>
              </tr>
              </thead>
              <tbody>
                  {% for res in resep %}
                  <tr>
                      {% if res.kategori == kategori %}
                        <td>{{res.namaResep}}</td>
                        <td><a href="{{res.url}}" target="_blank">{{res.url}}</a></td>
                      {% endif %} 
                  </tr>
              </tbody>
              {% endfor %}
    </form>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <title>{% block title%}Base{% endblock title %}</title>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  {% block additional_css %}
  {% endblock additional_css %}

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
  {% block js %}
  {% endblock js %}
</head>



<body>
  <nav class="navbar navbar-light" style="background-color: #b6d9f1;">
    <a class="navbar-brand" href="{% url 'main:home' %}">DINI.YL</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Resep
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'reseppage:kategori' %}">Tambah Resep</a>
          </div>
        </li>
    </div>
  </nav>
  {% block content %}
  {% endblock content %}
  {% block script %}
  {% endblock script%}
</body>

</html>